### ISSUE TITLE
Unloading

### ISSUE THREAD

**Issue by tommasoturchi** [mcneel/rhino.inside-cpython#4]
Hi!
I'm using rhino.inside in a python instance running Flask to take care of incoming requests. When the server is idle, I'm still billed for those core-hours, but it's not actually using Rhino, just running the server, so I was wondering whether there's a way to unload the Rhino Inside DLL and load it only when needed (perhaps with an unload method?). Is this behaviour planned?
Cheers!

Tommaso

**Comment by sbaer** [comment]
We aren't actively working on this feature, but it probably could be done by running a top level flask server that started and stopped a secondary server running rhino.
